version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    entrypoint: [ "sh", "-c", "chmod +x /wait-for-it.sh && /wait-for-it.sh db:5432 flyway -url=jdbc:postgresql://db:5432/product -user=postgres -password=password migrate" ]

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - flyway
    ports:
      - "8080:8080"
    restart: always
