spring:
  datasource:
    url: jdbc:postgresql://db:5432/product
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
